sudo: false

jdk:
  - openjdk8

language: scala

scala:
  - 2.13.0

script:
  - sbt ++$TRAVIS_SCALA_VERSION test

notifications:
  email:
    recipients:
      - ajax0615@gmail.com
    on_failure: always

before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt
